[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/emergency.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[redirects]]
  from = "/emergency"
  to = "/emergency.html"
  status = 200

[[redirects]]
  from = "/qr"
  to = "/index.html"
  status = 200